### PR TITLE
[Kotlin] Update ktor to 1.6

### PR DESCRIPTION
**Pull request by waghanza**

### CODE REVIEW

**Comment by waghanza** [comment]
@e5l @ilmirus could you give me a hand ? Using `ktor` **1.6** (gradle 7) [this app](https://github.com/the-benchmarker/web-frameworks/blob/master/kotlin/ktor/src/Application.kt) could not be compiled anymore

The full stack is
```
gradle@de5dfc748bdc:/usr/src/app$ gradle build

Welcome to Gradle 7.0.2!

Here are the highlights of this release:
 - File system watching enabled by default
 - Support for running with and building Java 16 projects
 - Native support for Apple Silicon processors
 - Dependency catalog feature preview

For more details see https://docs.gradle.org/7.0.2/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Task :compileKotlin
e: /usr/src/app/src/Application.kt: (22, 13): Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option
e: /usr/src/app/src/Application.kt: (24, 9): Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option
e: /usr/src/app/src/Application.kt: (25, 13): Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option
e: /usr/src/app/src/Application.kt: (28, 13): Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option

> Task :compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 42s
1 actionable task: 1 executed
```

**Comment by e5l** [comment]
It's because of new version of Kotlin. Since 1.5.0 the default bytecode target is 8. Could you check it with new Kotlin?

**Comment by waghanza** [comment]
You mean [kotlin 1.5.10](https://github.com/JetBrains/kotlin/releases/tag/v1.5.10) does not target jdk 8 anymore ?

**Comment by e5l** [comment]
It should. It looks like you're trying to build with 1.6 target.

**Comment by waghanza** [comment]
I think I've found the cause. 
https://github.com/the-benchmarker/web-frameworks/blob/4a270485c879e0247342de5545519882f1854eee/kotlin/ktor/build.gradle#L20 says that we require the **latest** version of `kotlin`, right ?
